### ISSUE TITLE
developer ux: make something like https://www.multicall3.com for P256 Verifier deployment/Precompile deployment

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/p256-verifier#18]
https://www.multicall3.com

cool down the line thing

**Comment by dcposch** [comment]
Yeah I love that

something like

**Address `0xc2b78104907F722DABAc4C69f826a522B2754De4`**

| Chain | Type | Gas price | Address |
|--------|--------|--------|--|
| **Ethereum** | contract | ~340k | 0xc2b78104907F722DABAc4C69f826a522B2754De4 |
| **Optimism** | contract | ~340k | 0xc2b78104907F722DABAc4C69f826a522B2754De4 |
| **Base** | **precompile** | **3450** | 0xc2b78104907F722DABAc4C69f826a522B2754De4 |
| **Arbitrum** | contract | ~340k | 0xc2b78104907F722DABAc4C69f826a522B2754De4 |
| **Polygon** | contract | ~340k | 0xc2b78104907F722DABAc4C69f826a522B2754De4 |

**Comment by nalinbhardwaj** [comment]
bought `p256.eth` earlier, can use that to point to the precompile and also host at `p256.eth.limo` if we want to.
